Repository Richard-Gist/actions-testing, pull requests merged in 2021-04, with the labels that each got.

#5 [issue1] - Added checkout to changelog step
  .github/workflows/changelog.yml
Labels: cla-signed

#7 [issue2] - Fixed issue 2
  README.md
Labels: cla-signed

#9 Fixes issue 8
  .github/workflows/changelog.yml
  TestingActions-iOS/ViewController.swift
  TestingActions-iOSTests/TestingActions_iOSTests.swift
Labels: cla-signed

#10 [pr1] - pr1 title
  README.md
Labels: cla-signed, enhancement

#11 [test-checkout] - need a pr
  README.md
Labels: cla-signed

#13 Make it like workflow
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/CI.yml
  .github/workflows/changelog.yml
  .github/workflows/ios.yml
  .github/workflows/release.yml
  .github/workflows/trunk.yml
  ActionTesting.podspec
  ActionTesting.xcodeproj/project.pbxproj
  ActionTesting.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ActionTesting.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ActionTesting.xcworkspace/contents.xcworkspacedata
  ActionTesting/AppDelegate.swift
  ActionTesting/Assets.xcassets/AccentColor.colorset/Contents.json
  ActionTesting/Assets.xcassets/AppIcon.appiconset/Contents.json
  ActionTesting/Assets.xcassets/Contents.json
  ActionTesting/Base.lproj/LaunchScreen.storyboard
  ActionTesting/Base.lproj/Main.storyboard
  ActionTesting/Info.plist
  ActionTesting/SceneDelegate.swift
  ActionTesting/ViewController.swift
  ActionTestingTests/ActionTestingTests.swift
  ActionTestingTests/Info.plist
  ActionTestingUITests/ActionTestingUITests.swift
  ActionTestingUITests/Info.plist
  Podfile
  Podfile.lock
  Pods/Manifest.lock
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/Target Support Files/Pods-ActionTesting-ActionTestingUITests/Pods-ActionTesting-ActionTestingUITests-Info.plist
  Pods/Target Support Files/Pods-ActionTesting-ActionTestingUITests/Pods-ActionTesting-ActionTestingUITests-acknowledgements.markdown
  Pods/Target Support Files/Pods-ActionTesting-ActionTestingUITests/Pods-ActionTesting-ActionTestingUITests-acknowledgements.plist
  Pods/Target Support Files/Pods-ActionTesting-ActionTestingUITests/Pods-ActionTesting-ActionTestingUITests-dummy.m
  Pods/Target Support Files/Pods-ActionTesting-ActionTestingUITests/Pods-ActionTesting-ActionTestingUITests-umbrella.h
  Pods/Target Support Files/Pods-ActionTesting-ActionTestingUITests/Pods-ActionTesting-ActionTestingUITests.debug.xcconfig
  Pods/Target Support Files/Pods-ActionTesting-ActionTestingUITests/Pods-ActionTesting-ActionTestingUITests.modulemap
  Pods/Target Support Files/Pods-ActionTesting-ActionTestingUITests/Pods-ActionTesting-ActionTestingUITests.release.xcconfig
  Pods/Target Support Files/Pods-ActionTesting/Pods-ActionTesting-Info.plist
  Pods/Target Support Files/Pods-ActionTesting/Pods-ActionTesting-acknowledgements.markdown
  Pods/Target Support Files/Pods-ActionTesting/Pods-ActionTesting-acknowledgements.plist
  Pods/Target Support Files/Pods-ActionTesting/Pods-ActionTesting-dummy.m
  Pods/Target Support Files/Pods-ActionTesting/Pods-ActionTesting-umbrella.h
  Pods/Target Support Files/Pods-ActionTesting/Pods-ActionTesting.debug.xcconfig
  Pods/Target Support Files/Pods-ActionTesting/Pods-ActionTesting.modulemap
  Pods/Target Support Files/Pods-ActionTesting/Pods-ActionTesting.release.xcconfig
  Pods/Target Support Files/Pods-ActionTestingTests/Pods-ActionTestingTests-Info.plist
  Pods/Target Support Files/Pods-ActionTestingTests/Pods-ActionTestingTests-acknowledgements.markdown
  Pods/Target Support Files/Pods-ActionTestingTests/Pods-ActionTestingTests-acknowledgements.plist
  Pods/Target Support Files/Pods-ActionTestingTests/Pods-ActionTestingTests-dummy.m
  Pods/Target Support Files/Pods-ActionTestingTests/Pods-ActionTestingTests-umbrella.h
  Pods/Target Support Files/Pods-ActionTestingTests/Pods-ActionTestingTests.debug.xcconfig
  Pods/Target Support Files/Pods-ActionTestingTests/Pods-ActionTestingTests.modulemap
  Pods/Target Support Files/Pods-ActionTestingTests/Pods-ActionTestingTests.release.xcconfig
  TestingActions-iOS.xcodeproj/project.pbxproj
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/README.md
Labels: cla-signed

#15 [more-logging] - Added in complex configuration
  .github/workflows/trunk.yml
  configuration_complex.json
Labels: cla-signed, enhancement

#16 [more-logging] - hey versions are important
  .github/workflows/trunk.yml
Labels: cla-signed, documentation, enhancement

#17 [more-logging] - Found some more things to try
  .github/workflows/trunk.yml
Labels: cla-signed

#18 [more-logging] - Increased fetchdepth and bumping minor
  .github/workflows/trunk.yml
Labels: cla-signed

#19 This one should work. I've done a bit more with it than before by adding quotes!
  .github/workflows/trunk.yml
Labels: cla-signed

#20 [more-logging] - Updated versioning to work better
  .github/workflows/trunk.yml
  fastlane/Fastfile
Labels: cla-signed

#21 [more-logging] - I was broken
  .github/workflows/trunk.yml
Labels: cla-signed

#23 [bugPR] - Bug cleaned
  README.md
Labels: bug, cla-signed

#24 [bugPR] - Now its a feature!
  README.md
Labels: cla-signed, enhancement

#25 Forgot to document
  README.md
Labels: cla-signed, documentation

#26 I am doing all the things
  README.md
Labels: bug, cla-signed, documentation, enhancement

#27 [bugPR] - Is it faster to delete then commit or just add the -m?
  README.md
Labels: cla-signed, duplicate, good first issue, help wanted, question, wontfix

#28 All the things
  README.md
Labels: bug, cla-signed, documentation, duplicate, enhancement, feature, good first issue, help wanted, invalid, question, wontfix

#32 All the things
  README.md
Labels: bug, cla-signed

#36 Update README.md
  .github/workflows/trunk.yml
  README.md
Labels: cla-signed

#37 Update README.md
  README.md
Labels: cla-signed

#38 Update README.md
  README.md
Labels: cla-signed

#33 Close something
  README.md
Labels: cla-signed

#39 Update README.md
  README.md
Labels: cla-signed

#40 Update README.md
  README.md
Labels: cla-signed

#41 Update README.md
  README.md
Labels: cla-signed

#42 Update README.md
  README.md
Labels: cla-signed

#43 Did we fix it?
  README.md
Labels: cla-signed

#44 Update README.md
  README.md
Labels: cla-signed

#45 Update README.md
  README.md
Labels: cla-signed

#46 Update README.md
  README.md
Labels: cla-signed

#49 Update Sonarcloud.yml
  .github/workflows/Sonarcloud.yml
Labels: cla-signed

#54 Update README.md
  README.md
Labels: cla-signed
